config/routes.rb
Rails.application.routes.draw do

  resources :tweets
	#routing our own resources
	# get 'foods' ,to: "foods#index" ,:as=>"foods"
	# get 'foods/new', to:"foods#new", :as=>"new_foods"
	# post 'foods' ,to:'foods#create'
	# get 'foods/:id/edit', to:"foods#edit" ,:as=>"edit_foods"

	# get 'foods/:id', to:"foods#show",:as=>"food"
	# patch 'foods/:id', to:"foods#update"
	# put 'foods/:id', to:"foods#update"
	# delete 'foods/:id', to:'foods#destroy'

  # resources :bois
  # resources :books
	# root 'foods#index'
	# root 'mains#index'
  root 'tweets#index'


	get'signup', to:'registrations#new'
  	post 'signup', to:'registrations#create' #creating a post url for create method 

  	#logout 
  	delete 'logout', to:'sessions#destroy'


  	#login method
  	get 'signin', to:'sessions#new' # this for getting the form
  	post 'signin', to:'sessions#create' # this is for posting the form

  	#edit password
  	get 'password/edit', to:'passwordedits#edit'
  	patch 'password/edit', to:'passwordedits#update'

      # user tweets
      get 'mytweets',to:'mains#my_tweets'
  #added a comment
  # For details on the DSL sid_available?able within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :logged_in?
  before_action :set_tweet,only: %i[ show edit update destroy ]

  # GET /tweets or /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user = Current.reg

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to root_path, notice: "Tweet was successfully created." }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to mytweets_path, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:title, :body, :user_id)
    end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.erb
<%= form_with(model: tweet) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field m-5">
    <div class="control">
      <%= form.label :title ,class:'label'%>
      <%= form.text_field :title ,class:'input'%>
    </div>
  </div>

  <div class="field m-5">
    <div class="control">
      
    <%= form.label :body,class:'label' %>
    <%= form.text_area :body,class:'textarea' %>
    </div>
  </div>

 

  <div class="actions m-5">
    <%= form.submit class:'button is-success' %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1 class="title m-5">Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<div class="m-5">
	<%= link_to 'Show', @tweet ,class:'button is-warning'%> 	
    <%= link_to 'Back', tweets_path ,class:'button is-link'%>
</div>

app/views/tweets/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<% @tweets.each do |tweet| %>
    <div class="card m-5 ">
    <div class="card-content">
      <div class="content">
        <h2> <%= tweet.title %> </h2>
        <p> <%= tweet.body %> </p>
      </div>
    </div>
  </div>
  <hr>
  <!-- <hr> -->
<% end %>

app/views/tweets/new.html.erb
<h1 class="title m-5">New Tweet</h1>

<%= render 'form', tweet: @tweet %>
 
<h6 class='button is-small mx-5 is-info is-outlined' ><%= link_to 'Back', tweets_path %></h6>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<div class="card m-5 ">
    <div class="card-content">
      <div class="content">
        <h2> <%= @tweet.title %> </h2>
        <p> <%= @tweet.body %> </p>
      </div>
      <%= link_to 'Back', tweets_path,class:'button is-link' %>		
      <%= link_to 'Edit', edit_tweet_path(@tweet),class:'button is-warning' %> 
    </div>
  </div>