config/routes.rb
Rails.application.routes.draw do

  resources :tweets
	#routing our own resources
	# get 'foods' ,to: "foods#index" ,:as=>"foods"
	# get 'foods/new', to:"foods#new", :as=>"new_foods"
	# post 'foods' ,to:'foods#create'
	# get 'foods/:id/edit', to:"foods#edit" ,:as=>"edit_foods"

	# get 'foods/:id', to:"foods#show",:as=>"food"
	# patch 'foods/:id', to:"foods#update"
	# put 'foods/:id', to:"foods#update"
	# delete 'foods/:id', to:'foods#destroy'

  # resources :bois
  # resources :books
	# root 'foods#index'
	# root 'mains#index'
  root 'tweets#index'


	get'signup', to:'registrations#new'
  	post 'signup', to:'registrations#create' #creating a post url for create method 

  	#logout 
  	delete 'logout', to:'sessions#destroy'


  	#login method
  	get 'signin', to:'sessions#new' # this for getting the form
  	post 'signin', to:'sessions#create' # this is for posting the form

  	#edit password
  	get 'password/edit', to:'passwordedits#edit'
  	patch 'password/edit', to:'passwordedits#update'

      # user tweets
      get 'mytweets',to:'mains#my_tweets'
  #added a comment
  # For details on the DSL sid_available?able within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/partials/_nav.html.erb
<nav class="navbar is-dark" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <!-- <a class="navbar-item" href="https://bulma.io"> -->
       <%#= link_to 'Root',root_path,class:'navbar-item' %>

      <!-- <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28"> -->
    <!-- </a> -->

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
       <%= link_to 'Home',root_path,class:'navbar-item' %>
      

      <%= link_to "Create a tweet",new_tweet_path,class:'navbar-item'  %>
     <% if Current.reg %>

          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">
              My Profile
            </a>

            <div class="navbar-dropdown">
              <%= link_to 'Change password',password_edit_path,class:'navbar-item'  %>
              
                
              <%= link_to "My tweets",mytweets_path,class:'navbar-item'  %>
              
              <a class="navbar-item">
                Contact
              </a>
              <!-- <hr class="navbar-divider"> -->
             <!--  <a class="navbar-item">
                Report an issue
              </a> -->
            </div>
          </div>
        <% end  %>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">

        <div class="buttons">
          <% if Current.reg %>
            <!-- <p>Hello,<%#= Current.reg.email %> </p> -->
        	<%= link_to 'Logout',logout_path,method: :delete,class:'button is-danger is-light' %>
          <% else %>

        	<%= link_to 'Sign up',signup_path,class:'button is-primary' %>
          <%= link_to 'Sign in',signin_path,class:'button is-light is-primary' %>
          <% end %>
          <!-- <a class="button is-primary">
            <strong>Sign up</strong>
          </a> -->

          <!-- <a class="button is-light">
            Log in
          </a> -->
        </div>
      </div>
    </div>
  </div>
</nav>