config/routes.rb
Rails.application.routes.draw do

  resources :tweets
	#routing our own resources
	# get 'foods' ,to: "foods#index" ,:as=>"foods"
	# get 'foods/new', to:"foods#new", :as=>"new_foods"
	# post 'foods' ,to:'foods#create'
	# get 'foods/:id/edit', to:"foods#edit" ,:as=>"edit_foods"

	# get 'foods/:id', to:"foods#show",:as=>"food"
	# patch 'foods/:id', to:"foods#update"
	# put 'foods/:id', to:"foods#update"
	# delete 'foods/:id', to:'foods#destroy'

  # resources :bois
  # resources :books
	# root 'foods#index'
	# root 'mains#index'
  root 'tweets#index'


	get'signup', to:'registrations#new'
  	post 'signup', to:'registrations#create' #creating a post url for create method 

  	#logout 
  	delete 'logout', to:'sessions#destroy'


  	#login method
  	get 'signin', to:'sessions#new' # this for getting the form
  	post 'signin', to:'sessions#create' # this is for posting the form

  	#edit password
  	get 'password/edit', to:'passwordedits#edit'
  	patch 'password/edit', to:'passwordedits#update'

      # user tweets
      get 'mytweets',to:'mains#my_tweets'
  #added a comment
  # For details on the DSL sid_available?able within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/mains_controller.rb
class MainsController < ApplicationController
	def index
		if session[:user_id]
			@user=User.find_by(id:session[:user_id])
			# if we use User.find and destroy the user in our db it will throw an error bcz it is still finding the destoryed id 

			#but if we use find_by method it will not throw an error bcoz if the user get destroyed this method will not forcely find the user
		end
	end
	def my_tweets
		if Current.reg.nil?
			redirect_to signin_path,notice:'You must be login'
		else
			@userTweets=Current.reg.tweets
		end
	end

end

app/views/mains/index.html.erb
<% if notice %>
  <h5 class="m-5 " style="color:green"><%= notice %></h5> 
<% end %>
<h1 class="title is-1 m-5">This is new thing</h1>
<% if @user %>
	 <h2 class="title is-3 m-5"> You are logged in as <%= @user.email %> </h2>
	 <%= button_to "Logout",logout_path,method: :delete,class:'button is-danger ml-5' %>
	 <h3> You have <%= @user.tweets.count %> tweets </h3>
<% end %>

app/views/mains/my_tweets.html.erb
<h1 class="title m-5">You have <%= pluralize(@userTweets.count,'tweet') %> </h1>

<% @userTweets.each do |tweet| %>
    <div class="card m-5 ">
    <div class="card-content">
      <div class="content">
        <h2> <%= tweet.title %> </h2>
        <p> <%= tweet.body %> </p>
      </div>
    </div>
  	<%= link_to "Edit",edit_tweet_path(tweet.id) ,class:'button is-info m-3' %>
  	<%= link_to "Delete",tweet_path(tweet.id),method: :delete,data:{
  		confirm:"Delete?"
  	} ,class:'button is-danger m-3' %>

  	<%= link_to "Show",tweet_path(tweet.id) ,class:'button is-warning  m-3' %>

  </div>
  <hr>
  <!-- <hr> -->
<% end %>